{% set name = "spython" %}
{% set version = "0.0.75" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57d39cdbef4cf307a8d608961aa4e043e3fe9b40b4ec63fd0d1e8c5976806b7a

build:
  number: 0
  noarch: python
  entry_points:
    - spython=spython.client:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3
    - pytest-runner
  run:
    - python >=3
    - requests
    - semver

test:
  imports:
    - spython
    - spython.client
    - spython.image
    - spython.image.cmd
    - spython.instance
    - spython.instance.cmd
    - spython.logger
    - spython.main
    - spython.main.base
    - spython.main.parse
    - spython.tests
    - spython.utils
  commands:
    - spython --help
  requires:
    - pytest

about:
  home: http://www.github.com/singularityhub/singularity-cli
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: Command line python tool for working with singularity.
  doc_url: https://singularityhub.github.io/singularity-cli/install
  dev_url: https://www.github.com/singularityhub/singularity-cli

extra:
  recipe-maintainers:
    - tschoonj
    - vsoch
