{% set name = "spython" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 143557849d636697ddd80e0ba95920efe4668351f5becce6bdc73a7651aa128d

build:
  number: 0
  noarch: python
  entry_points:
    - spython=spython.client:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3
    - pytest-runner
  run:
    - python >=3

test:
  imports:
    - spython
    - spython.client
    - spython.image
    - spython.instance
    - spython.instance.cmd
    - spython.logger
    - spython.main
    - spython.main.base
    - spython.main.parse
    - spython.tests
    - spython.utils
  commands:
    - spython --help
  requires:
    - pytest

about:
  home: http://github.com/singularityhub/singularity-cli
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: Command line python tool for working with singularity.
  doc_url: https://singularityhub.github.io/singularity-cli/install
  dev_url: https://github.com/singularityhub/singularity-cli

extra:
  recipe-maintainers:
    - tschoonj
    - vsoch
