travis:
  secure:
    BINSTAR_TOKEN: pmmyL6F/gE681xux+xECbBDD+eBK/Olrd1VSqRYP4cLy3alVzrsdRd4uu++N8R1LTJjTtSRU00mJ5zAWxN8GLfKZXe9vYk7qzvE20tuKKokLc4NiScwsz0PL6ppVBfHdRq/0RGOMrG/LzqFJMKo/jMQon7Ng1xfEn47bxc63jPEZHZDHmP/O6kNYkFixXqgZUyv4q05STA8Kp2Ppzz2WxvZSYKm5WZCEAACEdzN+rLt8KNyxyU7wr0zf/qr731xZ0NdeesabF7ioox2d2EGj4ViUqi3kLjI9pVg85jCe0Wk/Mnzeoxm8RVhmKgUrcONr+P8GuJhzQdoRNMUMAVaANP8YFhQ30lQsTnmZIyWWmpB7J5foNJ5k71ix8n139+RMPLEMn7jiYJpfh55H+tPiyC+fQCCurBvVuk+S4nFEjFuu6GILKmGyRqGQVCy7zaNkaaSTfBspCfsL2RaF1YS3gFkQqegG3uUmr/OoBeazqE9eOaPxCjrAwd4Rew64H/zME47Nvt6qq5WFzAx7HUCXq6kMl7xqZ5dOBgbkBzE5CVkk19QYY78po5eF1LCcx1p5+uPQlmof9I8Xm5m/W+EXpjOsm7wO7gKq2OocqPZOpQ1JdYrLLZmRi+HTkX/Aj++sZlO3zoHz1Q51+2Ch8lwcQ/imODP5kMieoToCgtb1lGM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
